/*Manage page action types */
export const MANAGE_PAGE_REQUEST = 'MANAGE_PAGE_REQUEST';
export const MANAGE_PAGE_SUCCESS = 'MANAGE_PAGE_SUCCESS';
export const MANAGE_PAGE_FAILURE = 'MANAGE_PAGE_FAILURE';

/*Delete page action types */
export const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST';
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS';
export const DELETE_PAGE_FAILURE = 'DELETE_PAGE_FAILURE';